name = "Neo Fossil"
author = "kodiitulip"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "56255f023306aca387e2a01815e76efffdd5834c1b6fb6910a918e86985bacf9"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"
