name = "Neo Fossil"
author = "kodiitulip"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "02b61c7b6dc71fa14aef2c5ef785d88ea9bb67875ddeac85aa54faa51e50a56c"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"
